### ISSUE TITLE
Frontend / admin: One SSID breaks config.yaml formatting for "network:"

### ISSUE THREAD

**Issue by posixpoet** [KasperskyLab/TinyCheck#25]
When removing all SSIDs unter admin page "MANAGE DEVICE/Network config" and leaving only one, the config.yaml modified.
The modification is subesquently parsed errornously.

Previous setting under "network:/ssids:" (config.yaml):
```
 ...
 network:
  in: wlan1
  internet_check: http://example.com
  out: wlan0
  ssids:
  - skynet
  - wireless
  tokenized_ssids: true
 ...
```

After removal of all and addtion of SSID "TEST":
```
 ...
 network:
  in: wlan1
  internet_check: http://example.com
  out: wlan0
  ssids: TEST
  tokenized_ssids: true
 ...

```
"TEST" is subsequently then rendered as SSIDs "T", "E", "S", "T".
Expected behaviour is restored when manualyl editing config.yaml to
```
 ...
  ssids: 
  - TEST
 ...
```
